"""Static descriptions for FoxDot/Renardo SynthDefs and effects."""

SYNTH_DESCRIPTIONS = {
    "play1": "Mono sample playback",
    "play2": "Stereo sample playback",
    "audioin": "Audio input from sound card channels",
    "noise": "LF noise-based sound",
    "dab": "High-pass filtered sawtooth blend",
    "varsaw": "Variable sawtooth wave",
    "lazer": "Complex modulated sawtooth",
    "growl": "Sine oscillator with saw modulation",
    "bass": "Tri/sawtooth/feedback sine blend",
    "dirt": "Sawtooth-based gritty sound",
    "crunch": "Noise-based percussive sound",
    "rave": "Dynamic stochastic synthesis",
    "scatter": "Modulated sawtooth pair",
    "charm": "Filtered sine/sawtooth combination",
    "bell": "Klank resonator instrument",
    "gong": "Klank with feedback modulation",
    "soprano": "Vibrato-modulated high sine",
    "dub": "Triangle/feedback sine blend",
    "viola": "Phase-modulated oscillator",
    "scratch": "Vibrato with frequency modulation",
    "klank": "Resonant filtered noise",
    "feel": "Klank-based warm resonance",
    "glass": "Klank-based bright resonance",
    "soft": "Klank-based soft resonance",
    "quin": "Klank-based quintet resonance",
    "pluck": "Plucked string sound",
    "spark": "Bright transient sound",
    "blip": "Short bright blip",
    "ripple": "Pulse-based ripple pattern",
    "creep": "Modulated creeping pattern",
    "star": "Sawtooth with complex phase modulation",
    "jbass": "ADSR-controlled bass",
    "orient": "Oriental-flavored synth",
    "zap": "Quick percussive zap",
    "marimba": "Marimba-like percussive tone",
    "fuzz": "Fuzzy distorted sound",
    "bug": "Glitchy bug-like sound",
    "pulse": "Pulse wave synth",
    "saw": "Sawtooth wave synth",
    "snick": "Short snick percussive",
    "twang": "Twangy plucked string",
    "karp": "Karplus-Strong plucked string",
    "arpy": "Arpeggiated synth tone",
    "nylon": "Nylon string guitar",
    "donk": "Percussive donk hit",
    "squish": "Squished modulated sound",
    "swell": "Swelling pad sound",
    "razz": "Razzy buzzing synth",
    "sitar": "Sitar-like resonant string",
    "piano": "MDA Piano emulation (requires SC3 plugins)",
    "sawbass": "Sawtooth bass",
    "prophet": "Prophet-style polysynth",
    "pads": "Sustained pad sound",
    "pasha": "Pasha atmospheric synth",
    "ambi": "Ambient atmospheric synth",
    "space": "Spacey reverberant synth",
    "keys": "Electric keys",
    "dbass": "Deep bass",
    "sinepad": "Sine wave pad",
    "loop": "Loop sample playback",
    "stretch": "Time-stretched sample playback",
}

FX_DESCRIPTIONS = {
    "vib": "Vibrato - pitch oscillation",
    "slide": "Slide to next note pitch",
    "slidefrom": "Slide from a pitch to current",
    "bend": "Pitch bend",
    "coarse": "Coarse granular effect",
    "striate": "Striated granular effect",
    "pshift": "Pitch shift",
    "hpf": "High-pass filter",
    "lpf": "Low-pass filter",
    "swell": "Volume swell envelope",
    "bpf": "Band-pass filter",
    "crush": "Bitcrusher distortion",
    "dist": "Distortion",
    "spin": "Stereo spinning panner",
    "cut": "Cut/gate effect",
    "room": "Reverb room size",
    "chop": "Amplitude chopping",
    "tremolo": "Tremolo amplitude modulation",
    "echo": "Echo/delay effect",
    "formant": "Formant vowel filter",
    "shape": "Waveshaping distortion",
    "drive": "Overdrive distortion",
}
